// USER ACTION TYPES
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGNIN_LOADING = 'SIGNIN_LOADING';
export const SIGNIN_FAILIURE = 'SIGNIN_FAILIURE';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNIN_SUCCESS';



// POST ACTION TYPE

export const SET_POST = 'SET_POST';
export const GET_POST = 'GET_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const SETPOST_SUCCESS = 'SETPOST_SUCCESS';
export const SETPOST_LOADING = 'SETPOST_LOADING';
export const SETPOST_FAILIURE = 'SETPOST_FAILIURE';
export const GETPOST_SUCCESS = 'GETPOST_SUCCESS';
export const GETPOST_LOADING = 'GETPOST_LOADING';
export const GETPOST_FAILIURE = 'GETPOST_FAILIURE';

//PROFILE ACTION TYPE

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILIURE = 'PROFILE_FAILIURE';
export const PROFILE_FOUND_SUCCESS = 'PROFILE_FOUND_SUCCESS';

//CONNECTION ACTION TYPE

export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_LOADING = 'CONNECTION_LOADING';
export const CONNECTION_FAILIURE = 'CONNECTION_FAILIURE';
export const SUGGESTION_SUCCESS = 'SUGGESTION_SUCCESS';
export const PENDING_SUCCESS = 'PENDING_SUCCESS';
export const SENT_SUCCESS = 'SENT_SUCCESS';
export const USERACTIVITY_SUCCESS = 'USERACTIVITY_SUCCESS';




//CONNECTION ACTION TYPE

export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const MESSAGE_FAILIURE = 'MESSAGE_FAILIURE';
export const SEND_SUCCESS = 'SEND_SUCCESS';
